### ISSUE TITLE
Resource class and PHP 7

### ISSUE THREAD

**Issue by vijayk2017** [razorpay/razorpay-php#55] opened 2017-10-12 17:52 UTC
In PHP 7 Resource is reserved keyword
And in razorpay-PHP there is Resource class and guess it needs update

**Comment by harman28** [comment] 2017-10-25 07:08
Thanks for reporting this. Closing this for now, as it is a duplicate of #37. Will post an update on that issue shortly.

**Closed by harman28** 2017-10-25 07:08 UTC
