### ISSUE TITLE
Redirect After Payment is done

### ISSUE THREAD

**Issue by Mayureshp007** [razorpay/razorpay-php#217] opened 2021-04-24 15:40 UTC
I want to redirect user to a new page depending on his payment status. I am using PHP sample code. 

**Payment Success** 
Redirect to https://mydomain.com/payment/success

**Payment Not Success** 
Redirect to https://mydomain.com/payment/not-success

_I tried to adding Callback URL Parameter in the checkout options but nothing no luck._

**Note:** My payment is capturing, I need to redirect users if the payment is done.

My Browser console after payment:
![image](https://user-images.githubusercontent.com/11387370/115964372-d2060800-a541-11eb-94bb-23e90051ee7d.png)

**Comment by Mayureshp007** [comment] 2021-05-23 16:02
Can Anyone answer plz?

**Comment by Whip** [comment] 2021-07-16 08:12
What are you using to redirect the user? Share that code. And that JS error needs to be fixed.

**Comment by ankitdas13** [comment] 2022-09-01 10:23
Hi @Mayureshp007 sorry for the delay ,there seems to be some issue with the JS code . if the issue is still persist can you please check this [code snippet](https://razorpay.com/docs/payments/server-integration/php/payment-gateway/build-integration/#code-to-add-pay-button) . let us know if you need any help

Closing this issue for now.

**Closed by ankitdas13** 2022-09-01 10:23 UTC
